matrix:
  OS_VERSION:
    - jessie
  IMAGE_TYPE:
    - curl
    - scm

clone:
  recursive: true

build:
  image: armhfbuild/alpine:3.2
  commands:
    - cd upstream; patch -p1 <../armhf.patch

publish:
  docker:
    file: upstream/$$OS_VERSION/$$IMAGE_TYPE/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/buildpack-deps
    tag: $$OS_VERSION-$$IMAGE_TYPE
    storage_driver: overlay

    # Caching
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: $$BRANCH
cache:
  mount:
    - docker/image.tar
