matrix:
  IMAGE_TAG:
    - jessie-curl
    - jessie-scm
    - jessie

build:
  image: armhfbuild/alpine:3.2
  commands:
    - apk add --update git
    - git clone --single-branch https://github.com/docker-library/buildpack-deps upstream
    - cd upstream; patch -p1 <../armhf.patch

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: upstream/$${IMAGE_TAG/-//}/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/buildpack-deps
    tag: $$IMAGE_TAG
    storage_driver: overlay

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
